name: Update Recent Commit Languages

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the action

jobs:
  update-languages:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Run Python script to update languages
      - name: Run Script to Update Languages
        run: |
          pip install requests
          python scripts/update_recent_langs.py

      # Step 4: Commit and push changes to RECENT_LANGUAGES.md
      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add RECENT_LANGUAGES.md
          git commit -m "Update recent commit languages"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

      # Step 5: Inject languages into README.md (optional)
      - name: Inject Languages into README.md
        run: |
          # Remove the old section and append the new one
          sed -i '/<!--START_SECTION:recent_langs-->/, /<!--END_SECTION:recent_langs-->/d' README.md
          cat RECENT_LANGUAGES.md >> README.md
          git add README.md
          git commit -m "Update README with recent languages"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
